### ISSUE TITLE
Iridium is not responding to code

### ISSUE THREAD

**Issue by anrt06** [mikalhart/IridiumSBD#17]
I have connected my Iridium SBD modem with Arduino Uno through 7,8 pins. In Basic send code, I have changed according to comments as SoftwareSerial. My iridium modem is working fine while sending AT commands to it but there is no response for this code. Kindly guide me.

**Comment by mikalhart** [comment]
@anrt06,

I suspect either (a) a wiring issue or (b) the RockBLOCK has been damaged.  For earlier (9602) versions of RockBLOCK this, alas, was possible.  

Closing for now.  Reopen if it seems appropriate.
