### ISSUE TITLE
Ambiguious function call compiling for teensy 3.1

### ISSUE THREAD

**Issue by NickShaffner** [mikalhart/IridiumSBD#4]
D:\vagabond\vendor\arduino\libraries\IridiumSBD\IridiumSBD.cpp: In member function 'int IridiumSBD::internalSendReceiveSBD(const char*, const uint8_t*, size_t, uint8_t*, size_t*)':
D:\vagabond\vendor\arduino\libraries\IridiumSBD\IridiumSBD.cpp:259:25: error: call of overloaded 'console(size_t&)' is ambiguous
D:\vagabond\vendor\arduino\libraries\IridiumSBD\IridiumSBD.cpp:259:25: note: candidates are:
In file included from D:\vagabond\vendor\arduino\libraries\IridiumSBD\IridiumSBD.cpp:25:0:
D:\vagabond\vendor\arduino\libraries\IridiumSBD\IridiumSBD.h:149:9: note: void IridiumSBD::console(FlashString) <near match>
D:\vagabond\vendor\arduino\libraries\IridiumSBD\IridiumSBD.h:149:9: note:   no known conversion for argument 1 from 'size_t {aka unsigned int}' to 'FlashString {aka const __FlashStringHelper*}'
D:\vagabond\vendor\arduino\libraries\IridiumSBD\IridiumSBD.h:150:9: note: void IridiumSBD::console(const char*) <near match>
D:\vagabond\vendor\arduino\libraries\IridiumSBD\IridiumSBD.h:150:9: note:   no known conversion for argument 1 from 'size_t {aka unsigned int}' to 'const char*'
D:\vagabond\vendor\arduino\libraries\IridiumSBD\IridiumSBD.h:151:9: note: void IridiumSBD::console(uint16_t)
D:\vagabond\vendor\arduino\libraries\IridiumSBD\IridiumSBD.h:152:9: note: void IridiumSBD::console(char)

**Comment by mikalhart** [comment]
Finally fixing this in new release...
