### ISSUE TITLE
Iriduim SBD code problem

### ISSUE THREAD

**Issue by weatherballoon** [mikalhart/IridiumSBD#6]
Hi mikalhart,
 I am trying to use the RockBlock wiht my arduino mega. I have used your codes and made sure everything was set up right but the only thing I am getting back is 
>>AT

<<AT

and thats it. Do you have any idea how to fix this so I can transmit my data?

**Comment by mikalhart** [comment]
One of three things: (1) you're not waiting long enough for the supercap to charge, (2) your wiring may be wrong, or (3) your RockBLOCK may have suffered some static damage to the regulator
