### ISSUE TITLE
Use variable setting, not hard coded default

### ISSUE THREAD

**Issue by appelflap** [mikalhart/IridiumSBD#8]
Could not create a pull request with only this change, because I also changed the Time library. But here is the change: ee1553da5458995087047bc4d657292011a0c284

**Comment by mikalhart** [comment]
Thank you @appelflap.  Good catch.

Hey, I saw your port to Arduino Time.h (from *nix time).  Can you explain what benefit that gave you?

M

**Comment by appelflap** [comment]
Only reason is that I couldn't find the time.h (lowercase 't') for the Arduino IDE. And it wasn't included in my IDE by default. I am using an Arduino pro mini from Sparkfun.
